# Generated by Django 4.1.3 on 2022-11-30 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Price')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Number')),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('busy', 'Busy'), ('booked', 'Booked')], default='empty', max_length=10, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Type')),
            ],
        ),
    ]
